AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  DomainName:
    Type: String
    Default: example.net
  FullDomainName:
    Type: String
    Default: example.net
  HostedZoneId:
    Type: String
  TargetDomainName:
    Type: String
    Default: example.net
Resources:
  DNSName:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Join ['', [!Ref 'DomainName', .]]
      RecordSets:
        - Name: !Ref 'FullDomainName'
          Type: A
          AliasTarget:
            HostedZoneId: !Ref HostedZoneId
            DNSName: !Ref TargetDomainName